"""empty message

Revision ID: 4447a7f989c5
Revises: e83e772cab82
Create Date: 2017-03-29 01:54:48.381163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4447a7f989c5'
down_revision = 'e83e772cab82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mirror', sa.Column('last_fetch_status', sa.String(), nullable=True))
    op.add_column('mirror', sa.Column('last_fetch_status_code', sa.Integer(), nullable=True))
    op.add_column('mirror', sa.Column('main', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mirror', 'main')
    op.drop_column('mirror', 'last_fetch_status_code')
    op.drop_column('mirror', 'last_fetch_status')
    # ### end Alembic commands ###
